"""Seed data ported from the titan-front mocks (``src/data/*`` and the hard-coded page data).

Image paths are relative to the frontend's ``public/`` directory; missing files are simply skipped.
Tournament dates are expressed relative to "now" so their derived status always matches the mock.
"""

RANK_TIERS = [
    {
        "slug": "bronze",
        "name": "Bronze",
        "min_points": 0,
        "description": "تولد یک جنگجو در میدان",
        "color_from": "#c97a3d",
        "color_to": "#7a4118",
        "glow": "rgba(201,122,61,.55)",
        "ornament": "lozenge",
    },
    {
        "slug": "silver",
        "name": "Silver",
        "min_points": 1500,
        "description": "خروج از سایه‌ها و شکار رقبا",
        "color_from": "#e7ebf0",
        "color_to": "#9aa0aa",
        "glow": "rgba(200,208,220,.55)",
        "ornament": "star",
    },
    {
        "slug": "gold",
        "name": "Gold",
        "min_points": 5000,
        "description": "کابوس حریفان؛ درخشش در اوج",
        "color_from": "#ffe07a",
        "color_to": "#c9932c",
        "glow": "rgba(255,205,90,.6)",
        "ornament": "crown",
    },
    {
        "slug": "platinum",
        "name": "Platinum",
        "min_points": 10000,
        "description": "ارباب بی‌نقص مسابقات؛ تشنه‌ی جاودانگی",
        "color_from": "#c9a6ff",
        "color_to": "#6b3fa0",
        "glow": "rgba(157,110,224,.6)",
        "ornament": "gem",
    },
    {
        "slug": "titan",
        "name": "Titan",
        "min_points": 20000,
        "description": "خدای بی‌رقیب میدان؛ اسطوره تایتان‌ها",
        "color_from": "#ff3b30",
        "color_to": "#3a0000",
        "glow": "rgba(255,40,30,.75)",
        "ornament": "titan",
    },
]

BADGES = [
    ("champion", "قهرمان", "trophy"),
    ("streak-master", "استاد برد پیاپی", "flame"),
    ("veteran", "کهنه‌کار", "shield"),
    ("headshot-king", "سلطان هدشات", "skull"),
    ("clutch-master", "استاد کلاچ", "swords"),
    ("sniper-elite", "تک‌تیرانداز نخبه", "skull"),
    ("builder-pro", "سازنده حرفه‌ای", "game"),
    ("ace-hunter", "شکارچی ایس", "swords"),
    ("survivor", "بازمانده", "shield"),
    ("pathfinder", "راه‌یاب", "globe"),
    ("goal-machine", "ماشین گل‌زنی", "trophy"),
    ("creative-genius", "نابغه خلاق", "gift"),
]

SEASONS = [
    {"number": 2, "name": "فصل ۲", "start_days": -200, "end_days": -91, "is_current": False},
    {"number": 3, "name": "فصل ۳", "start_days": -90, "end_days": 90, "is_current": True},
]

PLATFORMS = [
    ("pc", "PC", "pc.png"),
    ("playstation", "PlayStation", "ps.png"),
    ("xbox", "Xbox", "xbox.png"),
    ("nintendo", "Nintendo", "nintendo.png"),
    ("mobile", "Mobile", ""),
]

PRODUCT_CATEGORIES = [
    ("game-currency", "ارز بازی"),
    ("bundle", "باندل و اشتراک"),
    ("gift-card", "گیفت کارت"),
    ("wallet", "کیف پول"),
    ("game", "بازی"),
    ("gear", "تجهیزات"),
    ("premium-account", "اکانت پریمیوم"),
]

GAMES = [
    {
        "slug": "fortnite",
        "title": "فورتنایت",
        "title_en": "Fortnite",
        "genre": "بتل رویال",
        "description": "بازی بتل رویال محبوب با میلیون‌ها بازیکن فعال. در میدان نبرد فرود بیایید، سلاح جمع کنید "
        "و آخرین نفر باقی‌مانده باشید.",
        "accent_color": "#00D4FF",
        "accent_gradient": "linear-gradient(135deg, #00D4FF, #7B2FFF)",
        "is_featured": True,
        "images": {
            "cover_image": "images/games/fortnite-background.png",
            "background_image": "images/games/fortnite-background.png",
            "character_image": "images/games/fortnite-character.png",
            "icon_image": "images/categories/fortnite.png",
        },
    },
    {
        "slug": "valorant",
        "title": "ولورنت",
        "title_en": "Valorant",
        "genre": "شوتر تاکتیکی",
        "description": "شوتر تاکتیکی ۵ در مقابل ۵ با شخصیت‌های منحصربفرد. استراتژی، هدف‌گیری و کار تیمی کلید "
        "پیروزی هستند.",
        "accent_color": "#FF4655",
        "accent_gradient": "linear-gradient(135deg, #FF4655, #BD3944)",
        "is_featured": True,
        "images": {
            "cover_image": "images/games/valorant-background.png",
            "background_image": "images/games/valorant-background.png",
            "character_image": "images/games/valorant-character.png",
            "icon_image": "images/categories/valorant.png",
        },
    },
    {
        "slug": "apex-legends",
        "title": "ایپکس لجندز",
        "title_en": "Apex Legends",
        "genre": "بتل رویال",
        "description": "شوتر بتل رویال تیمی با لجندهای منحصربفرد. هر لجند قابلیت‌های خاص خود را دارد.",
        "accent_color": "#EF4444",
        "accent_gradient": "linear-gradient(135deg, #EF4444, #DC2626)",
        "is_featured": True,
        "images": {
            "cover_image": "images/games/apexlegends-background.png",
            "background_image": "images/games/apexlegends-background.png",
            "character_image": "images/games/apexlegends-character.png",
            "icon_image": "images/categories/apex.png",
        },
    },
    {
        "slug": "premium",
        "title": "اکانت‌های پریمیوم",
        "title_en": "Premium",
        "genre": "سرویس‌ها",
        "kind": "service",
        "description": "خرید اکانت‌های اسپاتیفای، تلگرام و...",
        "accent_color": "#1DB954",
        "accent_gradient": "linear-gradient(135deg, #1DB954, #0088cc)",
        "is_featured": True,
        "images": {"cover_image": "images/games/premium.png", "icon_image": "images/categories/premium.png"},
    },
    {"slug": "call-of-duty", "title": "کال آو دیوتی", "title_en": "Call of Duty", "genre": "شوتر"},
    {"slug": "ea-fc", "title": "ای‌ای اف‌سی", "title_en": "EA FC", "genre": "ورزشی"},
    {"slug": "pubg", "title": "پابجی", "title_en": "PUBG", "genre": "بتل رویال"},
    {"slug": "minecraft", "title": "ماینکرفت", "title_en": "Minecraft", "genre": "سندباکس"},
    {"slug": "cs2", "title": "کانتر استرایک ۲", "title_en": "CS 2", "genre": "شوتر تاکتیکی"},
    {"slug": "dota-2", "title": "دوتا ۲", "title_en": "Dota 2", "genre": "موبا"},
]

_INSTANT = "تحویل آنی — شارژ مستقیم اکانت"
_TOPUP_FEATURES = [
    {"title": "تضمین", "description": "بدون بن شدن", "icon": "shield"},
    {"title": "پشتیبانی", "description": "چت آنلاین", "icon": "chat"},
    {"title": "فعال‌سازی سریع", "description": "زیر ۱۵ دقیقه", "icon": "flame"},
]

_PRODUCTS = [
    # Products with options: every option has its own price (and optionally stock).
    # Variant tuples are (label, price, original_price[, stock]); the product price is derived from them.
    {
        "slug": "fortnite-vbucks",
        "title": "وی‌باکس فورتنایت (V-Bucks)",
        "subtitle": "شارژ مستقیم روی اکانت",
        "game": "fortnite",
        "category": "game-currency",
        "vendor": "Epic Games",
        "platforms": ["pc", "playstation", "xbox", "nintendo"],
        "delivery_type": "account",
        "is_bestseller": True,
        "popularity": 140,
        "image": "images/products/vbucks.png",
        "delivery_info": _INSTANT,
        "description": "با خرید وی‌باکس فورتنایت، بتل پس سیزن جدید را بخرید یا اسکین‌های جذاب آیتم شاپ را از "
        "آن خود کنید. وی‌باکس‌ها به صورت قانونی و با رسید معتبر روی اکانت اپیک گیمز، پلی‌استیشن یا "
        "ایکس‌باکس شما شارژ می‌شوند.",
        "features": _TOPUP_FEATURES,
        "tags": [
            "شارژ مستقیم روی اکانت",
            "قابل استفاده در همه پلتفرم‌ها",
            "رسید معتبر اپیک گیمز",
            "بدون خطر بن شدن",
        ],
        "specs": {"region": "Global", "delivery": "15 min"},
        "variants": [
            ("۱,۰۰۰ وی‌باکس", 299000, 350000),
            ("۲,۸۰۰ وی‌باکس", 749000, 870000, 4),
            ("۵,۰۰۰ وی‌باکس", 1199000, 1450000),
            ("۱۳,۵۰۰ وی‌باکس", 2999000, 3500000),
        ],
    },
    {
        "slug": "psn-gift-card",
        "title": "گیفت کارت پلی‌استیشن",
        "category": "gift-card",
        "vendor": "PlayStation",
        "platforms": ["playstation"],
        "popularity": 110,
        "delivery_info": "تحویل آنی — کد ۱۲ رقمی به ایمیل ارسال می‌شود",
        "description": "گیفت کارت PlayStation Store. اعتبار برای خرید بازی، DLC و اشتراک PS Plus. ریجن US.",
        "variants": [
            ("۱۰ دلاری", 590000, None),
            ("۲۵ دلاری", 1390000, None),
            ("۵۰ دلاری", 2750000, 2900000),
            ("۱۰۰ دلاری", 5400000, 5800000),
        ],
    },
    {
        "slug": "xbox-gift-card",
        "title": "گیفت کارت ایکس‌باکس",
        "category": "gift-card",
        "vendor": "Xbox",
        "platforms": ["xbox", "pc"],
        "popularity": 70,
        "delivery_info": "تحویل آنی — کد ۲۵ کاراکتری",
        "description": "گیفت کارت Microsoft Store. قابل استفاده برای خرید بازی، Game Pass و آیتم‌ها.",
        "variants": [
            ("۱۵ دلاری", 850000, None),
            ("۲۵ دلاری", 1390000, None),
            ("۵۰ دلاری", 2700000, None),
            ("۱۰۰ دلاری", 5300000, None),
        ],
    },
    {
        "slug": "steam-wallet",
        "title": "شارژ کیف پول استیم",
        "category": "wallet",
        "vendor": "Steam",
        "platforms": ["pc"],
        "popularity": 130,
        "delivery_info": "تحویل آنی — کد والت استیم",
        "description": "شارژ کیف پول استیم. بیش از ۳۰,۰۰۰ بازی در دسترس شما.",
        "variants": [
            ("۵ دلاری", 295000, None),
            ("۲۰ دلاری", 1150000, None),
            ("۵۰ دلاری", 2800000, 3000000),
            ("۱۰۰ دلاری", 5500000, 5900000),
        ],
    },
    {
        "slug": "valorant-points",
        "title": "پوینت ولورنت (VP)",
        "game": "valorant",
        "category": "game-currency",
        "vendor": "Riot Games",
        "platforms": ["pc"],
        "delivery_type": "account",
        "popularity": 90,
        "delivery_info": _INSTANT,
        "description": "Valorant Points برای خرید اسکین سلاح، بتل‌پس و بسته‌های ویژه.",
        "variants": [
            ("۴۷۵ VP", 180000, None),
            ("۱,۰۰۰ VP", 350000, None),
            ("۲,۰۵۰ VP", 690000, None),
            ("۵,۳۵۰ VP", 1690000, None),
        ],
    },
    {
        "slug": "ea-fc-points",
        "title": "اف‌سی پوینت (FC Points)",
        "game": "ea-fc",
        "category": "game-currency",
        "vendor": "EA Games",
        "platforms": ["pc", "playstation", "xbox"],
        "delivery_type": "account",
        "popularity": 60,
        "delivery_info": _INSTANT,
        "description": "FC Points برای باز کردن پک‌های بازیکن و شرکت در Draft.",
        "variants": [
            ("۱۰۰ FC Points", 49000, None),
            ("۵۰۰ FC Points", 220000, None),
            ("۲,۲۰۰ FC Points", 890000, 950000),
            ("۵,۹۰۰ FC Points", 2290000, None),
        ],
    },
    {
        "slug": "cod-points",
        "title": "سی‌پی کال آو دیوتی (COD Points)",
        "game": "call-of-duty",
        "category": "game-currency",
        "vendor": "Activision",
        "platforms": ["pc", "playstation", "xbox"],
        "delivery_type": "account",
        "popularity": 75,
        "delivery_info": _INSTANT,
        "description": "CP برای خرید بتل‌پس، اسکین اپراتور و بسته‌های سلاح.",
        "variants": [
            ("۲۰۰ CP", 99000, None),
            ("۱,۱۰۰ CP", 490000, None),
            ("۲,۴۰۰ CP", 950000, 1100000),
            ("۵,۰۰۰ CP", 1890000, None),
        ],
    },
    {
        "slug": "apex-coins",
        "title": "ایپکس کوین (Apex Coins)",
        "game": "apex-legends",
        "category": "game-currency",
        "vendor": "EA Games",
        "platforms": ["pc", "playstation", "xbox"],
        "delivery_type": "account",
        "popularity": 65,
        "delivery_info": _INSTANT,
        "description": "Apex Coins برای خرید لجند، اسکین و بتل‌پس.",
        "variants": [
            ("۱,۰۰۰ کوین", 420000, None),
            ("۲,۱۵۰ کوین", 850000, None),
            ("۴,۳۵۰ کوین", 1650000, None),
            ("۱۱,۵۰۰ کوین", 3990000, None),
        ],
    },
    {
        "slug": "pubg-uc",
        "title": "یوسی پابجی موبایل (UC)",
        "game": "pubg",
        "category": "game-currency",
        "vendor": "Krafton",
        "platforms": ["mobile"],
        "delivery_type": "account",
        "popularity": 85,
        "delivery_info": "تحویل آنی — شارژ با Player ID",
        "description": "UC برای خرید رویال پس، اسکین و آیتم‌های ویژه پابجی موبایل.",
        "variants": [
            ("۶۰ UC", 35000, None),
            ("۶۶۰ UC", 190000, None),
            ("۳,۰۰۰ UC", 790000, 890000),
            ("۸,۱۰۰ UC", 1990000, None),
        ],
    },
    {
        "slug": "google-play-gift-card",
        "title": "گیفت کارت گوگل پلی",
        "category": "gift-card",
        "vendor": "Google",
        "platforms": ["mobile"],
        "popularity": 95,
        "delivery_info": "تحویل آنی — کد ریدیم",
        "description": "گیفت کارت گوگل پلی. خرید بازی، اپلیکیشن و اشتراک از Google Play Store.",
        "variants": [("۱۰ دلاری", 590000, None), ("۲۵ دلاری", 1390000, None), ("۵۰ دلاری", 2750000, None)],
    },
    # Fixed-price products: one price set directly on the product.
    {
        "slug": "fortnite-crew-pack",
        "title": "فورتنایت کرو (Fortnite Crew Pack)",
        "subtitle": "اشتراک ماهانه",
        "game": "fortnite",
        "category": "bundle",
        "vendor": "Epic Games",
        "platforms": ["pc", "playstation", "xbox", "nintendo"],
        "price": 990000,
        "original_price": 1100000,
        "delivery_type": "account",
        "is_new": True,
        "popularity": 105,
        "image": "images/games/fortnite-character.png",
        "delivery_info": _INSTANT,
        "description": "اشتراک یک‌ماهه فورتنایت کرو: ۱,۰۰۰ وی‌باکس، بتل‌پس فعال و باندل اسکین انحصاری همان ماه.",
        "features": _TOPUP_FEATURES,
    },
    {
        "slug": "minecraft-java-edition",
        "title": "ماینکرفت جاوا ادیشن",
        "game": "minecraft",
        "category": "game",
        "vendor": "Mojang",
        "platforms": ["pc"],
        "price": 1190000,
        "popularity": 100,
        "delivery_info": "تحویل آنی — کد فعال‌سازی Mojang",
        "description": "نسخه اصلی ماینکرفت Java Edition. شامل تمام آپدیت‌های رایگان آینده.",
    },
    {
        "slug": "nintendo-eshop-35",
        "title": "گیفت کارت نینتندو ایشاپ ۳۵ دلاری",
        "category": "gift-card",
        "vendor": "Nintendo",
        "platforms": ["nintendo"],
        "price": 1950000,
        "popularity": 40,
        "delivery_info": "تحویل آنی — کد ۱۶ رقمی",
        "description": "گیفت کارت ۳۵ دلاری Nintendo eShop. خرید بازی‌های نینتندو سوییچ. ریجن US.",
    },
    # --- store page grid
    {
        "slug": "elden-crown-deluxe",
        "title": "Elden Crown",
        "subtitle": "نسخه دلوکس",
        "game": "premium",
        "category": "game",
        "platforms": ["pc"],
        "price": 2950000,
        "original_price": 3450000,
        "is_bestseller": True,
        "popularity": 150,
        "image": "images/products/p-game-1.jpg",
        "description": "نسخه دلوکس Elden Crown شامل بازی اصلی و تمام محتوای اضافه.",
    },
    {
        "slug": "red-frontier-premium",
        "title": "Red Frontier",
        "subtitle": "بسته پرمیوم",
        "game": "premium",
        "category": "game",
        "platforms": ["playstation"],
        "price": 2500000,
        "original_price": 4000000,
        "popularity": 95,
        "image": "images/products/p-game-3.jpg",
        "description": "بسته پرمیوم Red Frontier برای پلی‌استیشن.",
    },
    {
        "slug": "titan-pro-headset",
        "title": "هدست تایتان پرو",
        "subtitle": "۷.۱ فراگیر · بی‌سیم",
        "game": "apex-legends",
        "category": "gear",
        "platforms": ["pc"],
        "price": 7450000,
        "original_price": 9000000,
        "stock": 25,
        "delivery_type": "manual",
        "is_bestseller": True,
        "popularity": 90,
        "image": "images/products/p-headset.jpg",
        "description": "صدای فراگیر ۷.۱ و میکروفون جداشدنی، ساخته شده برای شب‌های طولانی رنکد.",
    },
    {
        "slug": "titan-k60-keyboard",
        "title": "کیبورد تایتان K60",
        "subtitle": "۶۰٪ · هات‌سواپ · RGB",
        "game": "valorant",
        "category": "gear",
        "platforms": ["pc"],
        "price": 5950000,
        "stock": 18,
        "delivery_type": "manual",
        "popularity": 88,
        "image": "images/products/p-keyboard.jpg",
        "description": "سوییچ‌های هات‌سواپ و نورپردازی RGB برای هر کلید.",
    },
    {
        "slug": "titan-m40-mouse",
        "title": "موس تایتان M40",
        "subtitle": "۱۶۰۰۰ DPI · بی‌سیم",
        "game": "fortnite",
        "category": "gear",
        "platforms": ["pc"],
        "price": 3450000,
        "stock": 30,
        "delivery_type": "manual",
        "is_new": True,
        "popularity": 80,
        "image": "images/products/p-mouse.jpg",
        "description": "موس بی‌سیم سبک با سنسور ۱۶۰۰۰ DPI.",
    },
    {
        "slug": "titan-gift-card-50",
        "title": "گیفت کارت تایتان",
        "subtitle": "۵۰ دلار اعتبار",
        "game": "premium",
        "category": "gift-card",
        "price": 2500000,
        "popularity": 160,
        "image": "images/products/p-controller.jpg",
        "description": "اعتبار هدیه برای خرید از فروشگاه تایتان.",
    },
    # --- product page recommendations
    {
        "slug": "titan-nova-controller",
        "title": "دسته بی‌سیم تایتان نوا",
        "category": "gear",
        "platforms": ["pc", "playstation"],
        "price": 2450000,
        "stock": 12,
        "delivery_type": "manual",
        "popularity": 50,
        "image": "images/products/p-controller.jpg",
    },
    {
        "slug": "pulse-65-keyboard",
        "title": "کیبورد مکانیکال پالس ۶۵",
        "category": "gear",
        "platforms": ["pc"],
        "price": 3190000,
        "stock": 9,
        "delivery_type": "manual",
        "popularity": 45,
        "image": "images/products/p-keyboard.jpg",
    },
    {
        "slug": "valor-agents-deluxe",
        "title": "بازی ولور ایجنتس - نسخه دلوکس",
        "category": "game",
        "platforms": ["pc"],
        "price": 890000,
        "popularity": 55,
        "image": "images/products/p-game-1.jpg",
    },
    {
        "slug": "pulse-x-headset-red",
        "title": "هدست پالس X - نسخه قرمز",
        "category": "gear",
        "platforms": ["pc", "playstation", "xbox"],
        "price": 4890000,
        "stock": 7,
        "delivery_type": "manual",
        "popularity": 42,
        "image": "images/products/p-headset.jpg",
    },
    {
        "slug": "viper-gaming-mouse",
        "title": "موس گیمینگ وایپر",
        "category": "gear",
        "platforms": ["pc"],
        "price": 1200000,
        "stock": 40,
        "delivery_type": "manual",
        "popularity": 48,
        "image": "images/products/p-mouse.jpg",
    },
    # --- premium accounts
    {
        "slug": "spotify-premium",
        "title": "اشتراک اسپاتیفای پریمیوم",
        "game": "premium",
        "category": "premium-account",
        "delivery_type": "account",
        "popularity": 70,
        "description": "اشتراک اسپاتیفای پریمیوم روی اکانت شخصی شما.",
        "variants": [("۱ ماهه", 249000, None), ("۳ ماهه", 690000, None), ("۱۲ ماهه", 2490000, 2990000)],
    },
    {
        "slug": "telegram-premium",
        "title": "تلگرام پریمیوم",
        "game": "premium",
        "category": "premium-account",
        "delivery_type": "account",
        "popularity": 66,
        "description": "فعال‌سازی تلگرام پریمیوم بدون نیاز به ورود به اکانت.",
        "variants": [("۳ ماهه", 590000, None), ("۶ ماهه", 1090000, None), ("۱۲ ماهه", 1990000, None)],
    },
]

_GEAR_FEATURES = [
    {"title": "ضمانت اصالت", "description": "۱۸ ماه گارانتی", "icon": "shield"},
    {"title": "پشتیبانی", "description": "چت آنلاین", "icon": "chat"},
    {"title": "ارسال سریع", "description": "۲ تا ۴ روز کاری", "icon": "flame"},
]
_DIGITAL_TAGS = ["تحویل آنی", "۱۰۰٪ قانونی و اورجینال", "پشتیبانی ۲۴ ساعته"]
_GEAR_TAGS = ["ضمانت اصالت کالا", "۱۸ ماه گارانتی", "ارسال به سراسر کشور"]
_SEED_DISCOUNT = 0.12  # every seeded price gets a ~12% "before discount" price so discount badges show


def _list_price(price: int) -> int:
    """A plausible pre-discount price, rounded to the nearest thousand toman."""
    return round(price * (1 + _SEED_DISCOUNT) / 1000) * 1000


def _complete(spec: dict) -> dict:
    """Fill in whatever a product entry leaves out so every product page is fully populated:
    feature boxes, description, delivery info, tags, specs and a discount (on each option, if any)."""
    spec = dict(spec)
    gear = spec.get("delivery_type") == "manual"
    spec.setdefault("features", _GEAR_FEATURES if gear else _TOPUP_FEATURES)
    spec.setdefault("tags", _GEAR_TAGS if gear else _DIGITAL_TAGS)
    spec.setdefault(
        "description",
        f"{spec['title']} با ضمانت اصالت از فروشگاه تایتان. "
        + ("ارسال سریع به سراسر کشور همراه با گارانتی معتبر." if gear else "تحویل آنی و پشتیبانی ۲۴ ساعته."),
    )
    spec.setdefault(
        "delivery_info",
        "ارسال ۲ تا ۴ روز کاری" if gear else "تحویل آنی — کد فعال‌سازی به ایمیل ارسال می‌شود",
    )
    if gear:
        spec.setdefault("specs", {"warranty": "۱۸ ماه", "condition": "نو و آکبند"})
    else:
        activation = "شارژ مستقیم اکانت" if spec.get("delivery_type") == "account" else "کد فعال‌سازی"
        spec.setdefault("specs", {"region": "Global", "delivery": "زیر ۱۵ دقیقه", "activation": activation})

    if spec.get("variants"):
        spec["variants"] = [
            (label, price, original or _list_price(price), *rest)
            for label, price, original, *rest in spec["variants"]
        ]
    elif not spec.get("original_price"):
        spec["original_price"] = _list_price(spec["price"])
    return spec


PRODUCTS = [_complete(product) for product in _PRODUCTS]


# (username, level, xp, favorite game, wins, matches, points, earnings USD, badges)
PLAYERS = [
    ("ShadowStrike", 87, 24500, "fortnite", 342, 520, 15420, 45000, ["champion", "streak-master", "veteran"]),
    ("NightWolf", 82, 21800, "valorant", 298, 480, 13890, 38000, ["champion", "headshot-king"]),
    ("PhoenixRise", 79, 19200, "apex-legends", 276, 460, 12650, 32000, ["champion", "clutch-master"]),
    ("CyberVenom", 75, 17600, "call-of-duty", 251, 430, 11200, 28000, ["veteran", "sniper-elite"]),
    ("IronBlade", 71, 15400, "fortnite", 234, 410, 10800, 25000, ["builder-pro"]),
    ("StormBreaker", 68, 14100, "valorant", 218, 395, 9870, 21000, ["ace-hunter"]),
    ("DarkMatter", 65, 12800, "pubg", 205, 380, 9200, 18000, ["survivor"]),
    ("VoidRunner", 62, 11500, "apex-legends", 192, 365, 8750, 15000, ["pathfinder"]),
    ("BlazeFury", 59, 10200, "ea-fc", 178, 350, 8100, 12000, ["goal-machine"]),
    ("PixelHunter", 56, 9100, "minecraft", 165, 340, 7650, 10000, ["creative-genius"]),
    ("ArcticFox", 53, 8200, "fortnite", 152, 320, 7200, 8500, []),
    ("ThunderBolt", 50, 7500, "call-of-duty", 140, 305, 6800, 7000, []),
    ("GhostReaper", 48, 6900, "valorant", 132, 290, 6400, 5800, []),
    ("NeonPulse", 45, 6200, "pubg", 121, 275, 5900, 4500, []),
    ("CosmicRay", 42, 5600, "apex-legends", 110, 260, 5500, 3200, []),
    ("SilverArrow", 40, 5100, "fortnite", 102, 248, 5100, 2800, []),
    ("TitanSlayer", 38, 4700, "call-of-duty", 95, 235, 4800, 2100, []),
    ("QuantumShift", 35, 4200, "ea-fc", 88, 222, 4400, 1800, []),
    ("MeteorCrash", 33, 3800, "pubg", 82, 210, 4100, 1500, []),
    ("OmegaForce", 30, 3400, "minecraft", 75, 198, 3800, 1200, []),
    # tournament page leaderboard
    ("Ali_Gamer99", 44, 3000, "valorant", 64, 82, 12450, 0, []),
    ("HeadshotKing", 41, 2500, "valorant", 58, 79, 11800, 0, ["headshot-king"]),
    ("ProSniper_IR", 40, 2200, "valorant", 55, 80, 11200, 0, []),
    ("Apex_Predator", 36, 1800, "apex-legends", 45, 59, 8900, 0, []),
    ("WraithMain", 34, 1500, "apex-legends", 40, 56, 8500, 0, []),
    ("OctaneRush", 33, 1400, "apex-legends", 38, 57, 8100, 0, []),
    ("NoobMaster", 37, 1600, "fortnite", 48, 63, 9400, 0, []),
    ("NinjaWannaBe", 35, 1500, "fortnite", 42, 60, 8900, 0, []),
    ("BuildGod", 34, 1300, "fortnite", 39, 59, 8400, 0, []),
    # team members from the team pages
    ("ShadowHunter", 28, 900, "valorant", 30, 50, 2400, 0, []),
    ("ProSniperX", 25, 700, "valorant", 22, 41, 1900, 0, []),
]

DEMO_USER = {
    "phone": "09123456789",
    "username": "TahaTitan",
    "full_name": "طاها",
    "email": "taha@example.com",
    "avatar_seed": 5,
    "favorite_game": "valorant",
    "wallet_balance": 1_450_000,
    "game_accounts": [
        ("اکانت اصلی فورتنایت", "pro_gamer_99", "fortnite"),
        ("اکانت ولورانت", "titan_slayer", "valorant"),
    ],
    # (name, presence, game) — the right-hand rail
    "friends": [
        ("Mia", "in_game", "valorant"),
        ("Alex", "online", None),
        ("Sara", "away", None),
        ("Kian", "online", None),
        ("Bita", "online", None),
        ("Arman", "away", None),
    ],
}

# name, tag, game, region, points, wins, losses (team leaderboard + names used across the mocks).
# Points of the Valorant bracket teams are ordered so standard seeding reproduces the mock bracket.
TEAMS = [
    ("Iran Titans", "valorant", 9600, 30, 9),
    ("Sentinels", "valorant", 9500, 26, 7),
    ("Fnatic", "valorant", 9400, 25, 8),
    ("Shadow Wolves", "valorant", 9240, 28, 4),
    ("Viper Squad", "valorant", 9100, 25, 6),
    ("Dark Phoenix", "valorant", 9000, 22, 9),
    ("Aim Bots", "valorant", 8900, 20, 9),
    ("Team Liquid", "valorant", 8800, 21, 10),
    ("Paper Rex", "valorant", 8700, 19, 10),
    ("G2 Esports", "valorant", 8600, 18, 11),
    ("Nova", "valorant", 8000, 12, 12),
    ("Wall Hackers", "valorant", 3200, 4, 9),
    ("Shadow Strike", "valorant", 5200, 10, 8),
    ("Crimson Fangs", "apex-legends", 8910, 19, 10),
    ("Apex Predators", "apex-legends", 8500, 17, 12),
    ("Legends Club", "apex-legends", 8100, 15, 14),
    ("Iron Falcons", "apex-legends", 4000, 6, 6),
    ("Night Phantoms", "fortnite", 8470, 16, 8),
    ("Storm Chasers", "fortnite", 8000, 14, 10),
    ("Build Masters", "fortnite", 7500, 12, 13),
    ("Neon Riders", "fortnite", 7900, 15, 7),
    ("Dark Eagles", "fortnite", 7200, 11, 9),
    ("Sniper Elite", "cs2", 6000, 13, 8),
    ("Dire Force", "dota-2", 6400, 14, 9),
    ("Radiant Glow", "dota-2", 6100, 12, 10),
    ("Ancient Guard", "dota-2", 5800, 10, 10),
    ("Roshan Hunters", "dota-2", 5500, 9, 11),
]

IRAN_TITANS_ROSTER = ["ShadowHunter", "ProSniperX", "GhostReaper", "StormBreaker"]

# Tournament dates are offsets (days) from now. ``reg`` = (opens, closes) offsets.
# ``entrants`` = confirmed participants to seed; ``results`` controls bracket progress:
#   None = no bracket, "first_round" = live with round 1 decided, "all" = completed.
TOURNAMENTS = [
    {
        "slug": "titan-zero-build-cup",
        "title": "جام زیرو بیلد تایتان",
        "game": "fortnite",
        "prize_pool": 10000,
        "currency": "USD",
        "max": 2000,
        "start": -1,
        "days": 2,
        "region": "me",
        "format_label": "تکی — ۳ مرحله",
        "results": "first_round",
        "entrants": 8,
        "featured": True,
        "viewers": 1284,
        "description": "بزرگ‌ترین تورنمنت زیرو بیلد فورتنایت در خاورمیانه. بدون ساخت‌وساز، فقط مهارت خالص.",
        "rules": [
            "هر بازیکن باید اکانت اپیک گیمز فعال داشته باشد",
            "حداقل سطح اکانت: ۱۰",
            "استفاده از چیت یا هک ممنوع است",
            "هر بازیکن فقط یکبار می‌تواند ثبت‌نام کند",
            "نتایج ۳۰ دقیقه پس از هر مرحله اعلام می‌شود",
        ],
        "prizes": [(1, "قهرمان", 5000, 800), (2, "نایب قهرمان", 3000, 500), (3, "سوم", 2000, 300)],
    },
    {
        "slug": "valorant-nightfall",
        "title": "ولورنت نایتفال",
        "game": "valorant",
        "team_size": 5,
        "prize_pool": 25000,
        "currency": "USD",
        "max": 16,
        "start": -2,
        "days": 5,
        "region": "me",
        "format_label": "تیمی ۵ نفره — حذفی",
        "results": "first_round",
        "entrants": 8,
        "teams": [
            "Shadow Wolves",
            "Viper Squad",
            "Aim Bots",
            "Team Liquid",
            "Paper Rex",
            "G2 Esports",
            "Nova",
            "Wall Hackers",
        ],
        "featured": True,
        "viewers": 856,
        "description": "مسابقات حرفه‌ای ولورنت با حضور بهترین تیم‌های خاورمیانه. ۵ روز رقابت فشرده.",
        "rules": [
            "هر تیم باید ۵ بازیکن اصلی و ۱ بازیکن ذخیره داشته باشد",
            "حداقل رنک: پلاتینیوم",
            "استفاده از باگ‌های بازی ممنوع است",
            "تمام بازیکنان باید از سرورهای خاورمیانه متصل شوند",
        ],
        "prizes": [(1, "قهرمان", 15000, 1000), (2, "نایب قهرمان", 7000, 600), (3, "سوم", 3000, 300)],
    },
    {
        "slug": "titan-fc-league",
        "title": "لیگ فوتبال تایتان",
        "game": "ea-fc",
        "prize_pool": 5000,
        "currency": "USD",
        "max": 512,
        "entry_fee": 50000,
        "start": 10,
        "days": 11,
        "reg": (-5, 9),
        "region": "ir",
        "format_label": "تکی — لیگ + حذفی",
        "entrants": 4,
        "description": "لیگ فوتبال تایتان. ابتدا مرحله گروهی و سپس مرحله حذفی.",
        "rules": ["هر بازیکن باید اکانت EA فعال داشته باشد", "مد بازی: FUT Champions", "نیمه‌ها ۶ دقیقه‌ای"],
    },
    {
        "slug": "cod-warzone-battle",
        "title": "نبرد وارزون",
        "game": "call-of-duty",
        "team_size": 3,
        "prize_pool": 15000,
        "currency": "USD",
        "max": 3000,
        "start": 13,
        "days": 2,
        "reg": (-3, 12),
        "region": "intl",
        "format_label": "تیم ۳ نفره — بتل رویال",
        "entrants": 0,
        "featured": True,
        "description": "بزرگ‌ترین تورنمنت وارزون تایتان. تیم‌های ۳ نفره از سراسر جهان.",
        "rules": ["هر تیم ۳ بازیکن", "مد بازی: بتل رویال", "استفاده از VPN ممنوع", "ضبط بازی الزامی است"],
    },
    {
        "slug": "minecraft-build-wars",
        "title": "جنگ سازندگان ماینکرفت",
        "game": "minecraft",
        "prize_pool": 2000,
        "currency": "USD",
        "max": 500,
        "start": 16,
        "days": 2,
        "reg": (2, 15),
        "region": "ir",
        "format_label": "تکی — خلاقیت",
        "entrants": 0,
        "description": "مسابقه ساخت‌وساز خلاقانه در ماینکرفت. در هر دور یک موضوع اعلام می‌شود.",
        "rules": ["مد بازی: Creative", "استفاده از مد ممنوع", "زمان هر دور: ۳۰ دقیقه", "داوری توسط ۳ داور"],
    },
    {
        "slug": "apex-arena-showdown",
        "title": "نمایش آرنا ایپکس",
        "game": "apex-legends",
        "team_size": 3,
        "prize_pool": 12000,
        "currency": "USD",
        "max": 16,
        "start": -20,
        "days": 2,
        "region": "intl",
        "format_label": "تیم ۳ نفره — آرنا",
        "results": "all",
        "entrants": 4,
        "teams": ["Crimson Fangs", "Apex Predators", "Legends Club", "Iron Falcons"],
        "description": "مسابقات آرنا ایپکس لجندز با حضور تیم‌های بین‌المللی.",
        "rules": ["هر تیم ۳ بازیکن", "مد بازی: Arenas", "هر تیم یک کاپیتان مشخص کند"],
        "prizes": [(1, "قهرمان", 7000, 900), (2, "نایب قهرمان", 3500, 500), (3, "سوم", 1500, 200)],
    },
    {
        "slug": "fortnite-ranked-arena",
        "title": "آرنا رنکد فورتنایت",
        "game": "fortnite",
        "prize_pool": 3000,
        "currency": "USD",
        "max": 16,
        "start": -28,
        "days": 2,
        "region": "ir",
        "format_label": "تکی — رنکد",
        "results": "all",
        "entrants": 8,
        "description": "مسابقات رنکد فورتنایت. بازیکنان بر اساس امتیاز آرنا رتبه‌بندی می‌شوند.",
        "rules": ["حداقل رنک آرنا: Division 7", "هر بازیکن ۱۰ بازی", "سیستم امتیازدهی: کیل + جایگاه"],
        "prizes": [(1, "قهرمان", 1500, 600), (2, "نایب قهرمان", 1000, 300), (3, "سوم", 500, 150)],
    },
    {
        "slug": "valorant-champions-series",
        "title": "سری قهرمانان ولورنت",
        "game": "valorant",
        "team_size": 5,
        "prize_pool": 50000,
        "currency": "USD",
        "max": 512,
        "entry_fee": 100000,
        "start": 25,
        "days": 10,
        "reg": (-2, 24),
        "region": "me",
        "format_label": "تیمی ۵ نفره — لیگ + حذفی",
        "best_of": 3,
        "entrants": 2,
        "teams": ["Shadow Wolves", "Viper Squad"],
        "description": "بزرگ‌ترین مسابقات ولورنت خاورمیانه با جایزه ۵۰ هزار دلاری.",
        "rules": ["هر تیم ۵ بازیکن اصلی + ۲ ذخیره", "حداقل رنک: دایموند", "تمام بازی‌ها BO3", "فینال BO5"],
    },
    {
        "slug": "cod-search-destroy",
        "title": "سرچ اند دیستروی",
        "game": "call-of-duty",
        "team_size": 4,
        "prize_pool": 7500,
        "currency": "USD",
        "max": 64,
        "entry_fee": 20000,
        "start": -35,
        "days": 2,
        "region": "ir",
        "format_label": "تیم ۴ نفره — حذفی",
        "results": "all",
        "entrants": 4,
        "description": "مسابقات Search & Destroy کال آو دیوتی. مد محبوب رقابتی با فرمت حذفی.",
        "rules": ["مد بازی: Search & Destroy", "هر تیم ۴ بازیکن", "تمام بازی‌ها BO3", "فینال BO5"],
    },
    {
        "slug": "pubg-mobile-masters",
        "title": "مسترز پابجی موبایل",
        "game": "pubg",
        "team_size": 4,
        "prize_pool": 20000,
        "currency": "USD",
        "max": 1500,
        "start": 20,
        "days": 5,
        "reg": (-1, 19),
        "region": "intl",
        "format_label": "اسکواد ۴ نفره",
        "entrants": 0,
        "description": "مسابقات بین‌المللی پابجی موبایل. بهترین اسکوادها از سراسر جهان.",
        "rules": ["فقط موبایل (امولاتور ممنوع)", "TPP", "مپ: Erangel", "هر اسکواد ۶ بازی"],
    },
    {
        "slug": "apex-predator-tournament",
        "title": "تورنمنت پردیتور ایپکس",
        "game": "apex-legends",
        "team_size": 3,
        "prize_pool": 18000,
        "currency": "USD",
        "max": 600,
        "entry_fee": 75000,
        "start": 30,
        "days": 3,
        "reg": (5, 29),
        "region": "me",
        "format_label": "تیم ۳ نفره — بتل رویال",
        "entrants": 0,
        "description": "تورنمنت ویژه بازیکنان سطح Predator. فقط بهترین‌ها دعوت شده‌اند.",
        "rules": ["حداقل رنک: Master", "تیم ۳ نفره", "مد: Battle Royale Ranked", "هر تیم ۸ بازی"],
    },
    # --- tournaments list / details pages (Toman prizes)
    {
        "slug": "titan-valorant-championship",
        "title": "مسابقات قهرمانی ولورانت - تایتان",
        "game": "valorant",
        "team_size": 5,
        "prize_pool": 50_000_000,
        "currency": "IRT",
        "max": 32,
        "entry_fee": 50000,
        "entry_fee_original": 150000,
        "start": 1,
        "days": 3,
        "reg": (-7, 0.9),
        "region": "ir",
        "format_label": "۵v۵ (تیمی) — حذفی",
        "best_of": 3,
        "entrants": 4,
        "teams": ["Shadow Wolves", "Viper Squad", "Aim Bots", "Dark Phoenix"],
        "featured": True,
        "description": "بزرگترین رقابت تیمی ایران با جایزه نقدی ۵۰ میلیون تومانی. تیم خود را آماده کنید و "
        "مهارت‌های خود را در بالاترین سطح به چالش بکشید.",
        "rules": [
            "استفاده از هرگونه چیت، گلیچ یا رفتار غیرورزشی منجر به حذف تیم می‌شود",
            "حضور ۱۵ دقیقه قبل از شروع مسابقه الزامی است",
            "مراحل نیمه‌نهایی و فینال Best of 3",
        ],
        "prizes": [
            (1, "تیم اول (قهرمان)", 30_000_000, 1000),
            (2, "تیم دوم (نایب قهرمان)", 15_000_000, 600),
            (3, "تیم سوم", 5_000_000, 300),
        ],
    },
    {
        "slug": "titan-apex-solo",
        "title": "تورنومنت انفرادی ایپکس - تایتان",
        "game": "apex-legends",
        "prize_pool": 30_000_000,
        "currency": "IRT",
        "max": 32,
        "entry_fee": 50000,
        "entry_fee_original": 150000,
        "start": 3,
        "days": 1,
        "reg": (-5, 2.9),
        "region": "ir",
        "format_label": "تک نفره (Solo)",
        "entrants": 4,
        "description": "بزرگترین رقابت تک‌نفره ایران. مهارت‌های فردی خود را به چالش بکشید و قهرمان شوید.",
        "rules": ["استفاده از چیت ممنوع است", "حضور ۱۵ دقیقه قبل از شروع مسابقه"],
        "prizes": [
            (1, "نفر اول", 18_000_000, 800),
            (2, "نفر دوم", 9_000_000, 400),
            (3, "نفر سوم", 3_000_000, 200),
        ],
    },
    {
        "slug": "titan-fortnite-squads",
        "title": "جام اسکواد فورتنایت",
        "game": "fortnite",
        "team_size": 4,
        "prize_pool": 20_000_000,
        "currency": "IRT",
        "max": 4,
        "start": 4,
        "days": 1,
        "reg": (-6, 3.9),
        "region": "ir",
        "format_label": "اسکواد ۴ نفره",
        "entrants": 4,
        "teams": ["Neon Riders", "Dark Eagles", "Night Phantoms", "Storm Chasers"],
        "description": "رقابت اسکوادهای فورتنایت. ظرفیت تکمیل شده است.",
        "rules": ["هر اسکواد ۴ بازیکن", "مد: Zero Build"],
    },
    {
        "slug": "titan-cs2-major",
        "title": "مسابقات بزرگ کانتر استرایک ۲",
        "game": "cs2",
        "team_size": 5,
        "prize_pool": 100_000_000,
        "currency": "IRT",
        "max": 16,
        "entry_fee": 200000,
        "start": 7,
        "days": 3,
        "reg": (2, 6.5),
        "region": "ir",
        "format_label": "۵v۵ — حذفی",
        "entrants": 0,
        "description": "بزرگ‌ترین مسابقات CS2 تایتان. ثبت‌نام به‌زودی آغاز می‌شود.",
        "rules": ["هر تیم ۵ بازیکن", "تمام بازی‌ها BO3"],
    },
    {
        "slug": "titan-dota2-champions",
        "title": "جام قهرمانان دوتا ۲",
        "game": "dota-2",
        "team_size": 5,
        "prize_pool": 80_000_000,
        "currency": "IRT",
        "max": 16,
        "start": -1,
        "days": 3,
        "region": "me",
        "format_label": "۵v۵ — حذفی",
        "results": "first_round",
        "entrants": 4,
        "teams": ["Dire Force", "Radiant Glow", "Ancient Guard", "Roshan Hunters"],
        "description": "مسابقات دوتا ۲ با حضور بهترین تیم‌های منطقه.",
        "rules": ["هر تیم ۵ بازیکن", "Captain's Mode"],
    },
    {
        "slug": "titan-valorant-weekly",
        "title": "کاپ هفتگی ولورانت",
        "game": "valorant",
        "team_size": 5,
        "prize_pool": 10_000_000,
        "currency": "IRT",
        "max": 16,
        "start": 1,
        "days": 1,
        "reg": (-3, 0.8),
        "region": "ir",
        "format_label": "۵v۵ — حذفی",
        "entrants": 2,
        "teams": ["Aim Bots", "Wall Hackers"],
        "description": "کاپ هفتگی ولورانت برای تیم‌های تازه‌وارد و آماتور.",
        "rules": ["هر تیم ۵ بازیکن", "تمام بازی‌ها BO1"],
    },
    # --- the dashboard bracket page: Iran Titans in a live semi-final
    {
        "slug": "valorant-season-cup",
        "title": "تورنومنت فصلی ولورانت",
        "game": "valorant",
        "team_size": 5,
        "prize_pool": 40_000_000,
        "currency": "IRT",
        "max": 8,
        "start": -2,
        "days": 4,
        "region": "ir",
        "format_label": "۵v۵ — حذفی",
        "results": "mock_bracket",
        "entrants": 8,
        "teams": [
            "Iran Titans",
            "Sentinels",
            "Fnatic",
            "Dark Phoenix",
            "Team Liquid",
            "Paper Rex",
            "G2 Esports",
            "Nova",
        ],
        "description": "تورنومنت فصلی ولورانت تایتان. وضعیت لحظه‌ای رقابت‌ها و جایگاه تیم‌ها.",
        "rules": ["هر تیم ۵ بازیکن", "نیمه‌نهایی و فینال BO3"],
        "prizes": [
            (1, "قهرمان", 25_000_000, 1000),
            (2, "نایب قهرمان", 10_000_000, 500),
            (3, "سوم", 5_000_000, 250),
        ],
    },
]

# Round-1 results of the bracket page mock, in bracket order (seed1 v seed8, seed4 v seed5, …).
MOCK_BRACKET_SCORES = {
    "round_1": [(13, 8), (13, 11), (13, 9), (13, 10)],
    "round_2_completed": {1: (13, 11)},  # Sentinels beat Fnatic
    "round_2_live": 0,  # Iran Titans vs Dark Phoenix is live
}

PROMOS = [
    {
        "placement": "store_discount",
        "title": "باندل ویژه Valorant",
        "subtitle": "پکیج کامل اسکین‌های پرایم",
        "price": 2_100_000,
        "original_price": 3_500_000,
        "discount_label": "۴۰٪",
        "badge": "پیشنهاد ویژه",
        "image": "images/games/valorant-character.png",
        "background_image": "images/discount.png",
        "product": "valorant-points",
        "layout": {"scale": 1.15, "x": 0, "y": 0},
        "ends_in_seconds": 30 * 24 * 3600,
    },
    {
        "placement": "store_discount",
        "title": "Elden Crown",
        "subtitle": "نسخه دلوکس",
        "price": 2_950_000,
        "original_price": 3_450_000,
        "discount_label": "۱۵٪",
        "badge": "پیشنهاد ویژه",
        "image": "images/banner-hero.png",
        "background_image": "images/discount.png",
        "product": "elden-crown-deluxe",
        "layout": {"scale": 1.1, "x": 0, "y": 0},
        "ends_in_seconds": 30 * 24 * 3600,
    },
    {
        "placement": "store_bestseller",
        "title": "باندل ویژه Apex",
        "subtitle": "شامل اسکین اپیک و ۱۰۰۰ کوین",
        "price": 2_950_000,
        "badge": "پرفروش‌ها",
        "image": "images/games/apexlegends-character.png",
        "background_image": "images/games/apexlegends-background.png",
        "background_gradient": "linear-gradient(135deg, rgba(30, 15, 35, 0.85) 0%, rgba(15, 5, 20, 0.98) 100%)",
        "product": "apex-coins",
        "layout": {"scale": 1.05, "x": -15, "y": 0},
    },
    {
        "placement": "store_bestseller",
        "title": "باندل ویژه Fortnite",
        "subtitle": "اسکین لجندری + ۲۰۰۰ وی‌باکس",
        "price": 4_500_000,
        "badge": "پرفروش‌ها",
        "image": "images/games/fortnite-character.png",
        "background_image": "images/games/fortnite-background.png",
        "background_gradient": "linear-gradient(135deg, rgba(20, 30, 80, 0.85) 0%, rgba(5, 10, 30, 0.98) 100%)",
        "product": "fortnite-vbucks",
        "layout": {"scale": 1.1, "x": 0, "y": 0},
    },
    {
        "placement": "tournament_hero",
        "title": "میدان نبردِ قهرمانان",
        "subtitle": "در رقابت‌های نفس‌گیر تایتان شرکت کنید و سهمی از جوایز نقدی این فصل ببرید.",
        "price": 50_000,
        "original_price": 150_000,
        "badge": "فصل ۳ مسابقات",
        "image": "images/banner-hero.png",
        "tournament": "titan-valorant-championship",
    },
    {
        "placement": "home_hero",
        "title": "تورنمنت‌های تایتان",
        "subtitle": "جوایز نقدی بزرگ در انتظار شماست. تیم خود را ثبت‌نام کنید.",
        "badge": "رقابت با بهترین‌ها",
        "image": "images/tournoment-banner.png",
        "link": "/tournament",
    },
]

ANNOUNCEMENTS = [
    (
        "Valorant Titan Cup",
        "ثبت‌نام تا 10 دقیقه دیگر بسته می‌شود",
        "trophy",
        "/tournaments/titan-valorant-weekly",
    ),
    ("فروش ویژه", "هدست تایتان پرو — 20٪ تخفیف برای یک ساعت آینده", "bag", "/product/titan-pro-headset"),
    ("سری راکت", "براکت دور دوم شروع شد", "trophy", "/tournaments/valorant-season-cup"),
]

CONTACT_CHANNELS = [
    {
        "kind": "discord",
        "title": "سرور دیسکورد تایتان",
        "description": "پیوستن به هزاران گیمر، پیدا کردن هم‌تیمی و گفتگو با تیم مدیریت",
        "url": "https://discord.gg/titan",
        "icon": "icons/discord.png",
        "action_label": "عضویت",
        "is_primary": True,
    },
    {
        "kind": "telegram_channel",
        "title": "کانال تلگرام",
        "description": "اخبار آپدیت‌ها، تخفیف‌ها و تورنمنت‌ها",
        "url": "https://t.me/titan_news",
        "icon": "icons/speaker.png",
    },
    {
        "kind": "telegram_support",
        "title": "پشتیبانی تلگرام",
        "description": "پیگیری سریع سفارش‌ها و مشکلات اکانت",
        "url": "https://t.me/titan_support",
        "icon": "icons/telegram.png",
    },
    {
        "kind": "live_chat",
        "title": "پشتیبانی زنده",
        "description": "چت مستقیم در سایت با کارشناسان ما",
        "url": "https://titan.ir/support/chat",
        "icon": "icons/support.png",
        "is_online": True,
    },
    {
        "kind": "email",
        "title": "ایمیل سازمانی",
        "description": "ارتباطات رسمی، پیشنهادها و انتقادها",
        "url": "mailto:support@titan.ir",
        "icon": "icons/email.png",
    },
    {
        "kind": "phone",
        "title": "پشتیبانی تلفنی",
        "description": "همه روزه از ۹ صبح تا ۱۰ شب",
        "url": "tel:+982112345678",
        "icon": "icons/telephon-call.png",
    },
]

REVIEW_COMMENTS = [
    "خیلی سریع تحویل شد، ممنون از تایتان!",
    "کیفیت عالی و پشتیبانی خوب.",
    "قیمت مناسب‌تر از جاهای دیگه بود.",
    "همه چیز درست و قانونی، پیشنهاد می‌کنم.",
    "",
]
