# Generated by Django 5.2.17 on 2026-10-03 12:30

import apps.accounts.models
import apps.core.fields
import apps.core.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='mobile number')),
                ('username', models.CharField(blank=True, max_length=32, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_.]{3,32}$', 'Username may contain 3-32 English letters, digits, dots and underscores.', code='invalid_username')], verbose_name='game ID')),
                ('full_name', models.CharField(blank=True, max_length=120, verbose_name='full name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp']), apps.core.validators.MaxFileSizeValidator()])),
                ('avatar_seed', models.PositiveSmallIntegerField(default=apps.accounts.models.random_avatar_seed)),
                ('level', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0, help_text='Progress inside the current level.')),
                ('points', models.PositiveIntegerField(db_index=True, default=0, help_text='Drives the rank tier.')),
                ('presence_status', models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('in_game', 'In game'), ('offline', 'Offline')], default='online', max_length=10)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], db_index=True, default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GameAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80, verbose_name='title')),
                ('username', models.CharField(max_length=150, verbose_name='username or email')),
                ('password', apps.core.fields.EncryptedTextField(blank=True, verbose_name='password')),
            ],
            options={
                'ordering': ['created_at'],
                'permissions': [('reveal_password', 'Can reveal game account passwords')],
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=11)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('change_phone', 'Change phone')], max_length=20)),
                ('code_hash', models.CharField(max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RankTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('min_points', models.PositiveIntegerField(unique=True)),
                ('color_from', models.CharField(max_length=32)),
                ('color_to', models.CharField(max_length=32)),
                ('glow', models.CharField(max_length=40)),
                ('ornament', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['min_points'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['awarded_at'],
            },
        ),
    ]
