# Generated by Django 5.2.17 on 2026-10-03 12:30

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('payments', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=60)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-number'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='one_current_season')],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='tournaments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp']), apps.core.validators.MaxFileSizeValidator()])),
                ('participant_type', models.CharField(choices=[('solo', 'Solo'), ('team', 'Team')], max_length=4)),
                ('team_size', models.PositiveSmallIntegerField(default=1, help_text='Players per team; 1 for solo.')),
                ('format', models.CharField(choices=[('single_elimination', 'Single elimination')], default='single_elimination', max_length=30)),
                ('format_label', models.CharField(blank=True, help_text='e.g. "5v5 — knockout"', max_length=80)),
                ('best_of', models.PositiveSmallIntegerField(default=1)),
                ('region', models.CharField(choices=[('me', 'Middle East'), ('eu', 'Europe'), ('ir', 'Iran'), ('intl', 'International')], default='me', max_length=4)),
                ('max_participants', models.PositiveIntegerField()),
                ('entry_fee', models.PositiveBigIntegerField(default=0, verbose_name='entry fee (toman)')),
                ('entry_fee_original', models.PositiveBigIntegerField(blank=True, null=True)),
                ('prize_pool', models.PositiveBigIntegerField(default=0)),
                ('prize_currency', models.CharField(choices=[('IRT', 'Toman'), ('USD', 'US dollar')], default='IRT', max_length=3)),
                ('rules', models.JSONField(blank=True, default=list)),
                ('registration_opens_at', models.DateTimeField()),
                ('registration_closes_at', models.DateTimeField()),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('viewer_count', models.PositiveIntegerField(default=0)),
                ('stream_url', models.URLField(blank=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='catalog.game')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='tournaments.season')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Awaiting payment'), ('confirmed', 'Confirmed'), ('withdrawn', 'Withdrawn'), ('cancelled', 'Cancelled')], db_index=True, max_length=20)),
                ('entry_fee_paid', models.PositiveBigIntegerField(default=0)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('seed', models.PositiveIntegerField(blank=True, null=True)),
                ('final_placement', models.PositiveIntegerField(blank=True, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.payment')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['seed', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round', models.PositiveSmallIntegerField(help_text='1 is the first round.')),
                ('position', models.PositiveSmallIntegerField(help_text='0-based index inside the round.')),
                ('score_a', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_b', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Waiting for participants'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('bye', 'Bye')], db_index=True, default='pending', max_length=10)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('best_of', models.PositiveSmallIntegerField(default=1)),
                ('next_slot', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B')], max_length=1)),
                ('lobby_code', models.CharField(blank=True, help_text='Only visible to the participants.', max_length=40)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('next_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeder_matches', to='tournaments.match')),
                ('participant_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.registration')),
                ('participant_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.registration')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.registration')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['round', 'position'],
            },
        ),
        migrations.CreateModel(
            name='TournamentPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveSmallIntegerField()),
                ('label', models.CharField(blank=True, max_length=60)),
                ('amount', models.PositiveBigIntegerField(default=0, help_text="In the tournament's prize currency.")),
                ('points', models.PositiveIntegerField(default=0, help_text='Rank points for every player at this place.')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['place'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tournaments.registration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('registration', 'user'), name='unique_registration_member')],
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(db_index=True, default=0)),
                ('tournaments_played', models.PositiveIntegerField(default=0)),
                ('tournaments_won', models.PositiveIntegerField(default=0)),
                ('earnings_irt', models.PositiveBigIntegerField(default=0)),
                ('earnings_usd', models.PositiveBigIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tournaments.season')),
            ],
            options={
                'verbose_name_plural': 'player stats',
                'ordering': ['-points', '-wins'],
                'constraints': [models.UniqueConstraint(fields=('user', 'game', 'season'), name='unique_player_stats')],
            },
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(db_index=True, default=0)),
                ('tournaments_played', models.PositiveIntegerField(default=0)),
                ('tournaments_won', models.PositiveIntegerField(default=0)),
                ('earnings_irt', models.PositiveBigIntegerField(default=0)),
                ('earnings_usd', models.PositiveBigIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.game')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tournaments.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='teams.team')),
            ],
            options={
                'verbose_name_plural': 'team stats',
                'ordering': ['-points', '-wins'],
                'constraints': [models.UniqueConstraint(fields=('team', 'game', 'season'), name='unique_team_stats')],
            },
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(condition=models.Q(('registration_closes_at__gte', models.F('registration_opens_at'))), name='registration_window_valid'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gte', models.F('starts_at'))), name='tournament_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(condition=models.Q(('max_participants__gte', 2)), name='tournament_min_participants'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('player__isnull', True), ('team__isnull', False)), models.Q(('player__isnull', False), ('team__isnull', True)), _connector='OR'), name='registration_team_xor_player'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending_payment', 'confirmed'])), fields=('tournament', 'team'), name='unique_active_team_registration'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending_payment', 'confirmed'])), fields=('tournament', 'player'), name='unique_active_player_registration'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('tournament', 'round', 'position'), name='unique_match_slot'),
        ),
        migrations.AddConstraint(
            model_name='tournamentprize',
            constraint=models.UniqueConstraint(fields=('tournament', 'place'), name='unique_prize_place'),
        ),
    ]
