# Generated by Django 5.2.17 on 2026-10-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_review_author'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='participant_type',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='team_size',
            field=models.PositiveSmallIntegerField(default=1, help_text='Players in each lineup. 1 makes it a solo tournament.'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(condition=models.Q(('team_size__gte', 1)), name='tournament_team_size_positive'),
        ),
    ]
