# Generated by Django 5.2.17 on 2026-10-03 12:30

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('text', models.CharField(max_length=250)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('discord', 'Discord'), ('telegram_channel', 'Telegram channel'), ('telegram_support', 'Telegram support'), ('live_chat', 'Live chat'), ('email', 'Email'), ('phone', 'Phone')], max_length=20)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('url', models.CharField(help_text='https://…, mailto:… or tel:…', max_length=300)),
                ('icon', models.ImageField(blank=True, upload_to='contact/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp']), apps.core.validators.MaxFileSizeValidator()])),
                ('action_label', models.CharField(blank=True, max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement', models.CharField(choices=[('store_discount', 'Store — special offers'), ('store_bestseller', 'Store — best sellers'), ('home_hero', 'Home — hero'), ('tournament_hero', 'Tournaments — hero')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('badge', models.CharField(blank=True, max_length=40)),
                ('image', models.ImageField(blank=True, upload_to='promos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp']), apps.core.validators.MaxFileSizeValidator()])),
                ('background_image', models.ImageField(blank=True, upload_to='promos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp']), apps.core.validators.MaxFileSizeValidator()])),
                ('background_gradient', models.CharField(blank=True, max_length=200)),
                ('price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('original_price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('discount_label', models.CharField(blank=True, max_length=20)),
                ('link', models.CharField(blank=True, help_text='Internal path or absolute URL.', max_length=300)),
                ('layout', models.JSONField(blank=True, default=dict, help_text='Art placement, e.g. {"scale": 1.1, "x": 0}')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Drives the countdown on the banner.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promos', to='catalog.product')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promos', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['placement', 'sort_order', '-created_at'],
            },
        ),
    ]
