# Generated by Django 5.2.17 on 2026-10-03 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.PositiveBigIntegerField(default=0, verbose_name='balance (toman)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(help_text='Positive for credit, negative for debit.')),
                ('kind', models.CharField(choices=[('topup', 'Top-up'), ('order_payment', 'Order payment'), ('tournament_fee', 'Tournament entry fee'), ('refund', 'Refund'), ('prize', 'Prize'), ('adjustment', 'Manual adjustment')], max_length=20)),
                ('balance_after', models.PositiveBigIntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('reference', models.CharField(blank=True, help_text='e.g. "order:TTN-…"', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.wallet')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveBigIntegerField(verbose_name='amount (toman)')),
                ('gateway', models.CharField(max_length=20)),
                ('purpose', models.CharField(choices=[('order', 'Order'), ('tournament_registration', 'Tournament registration'), ('wallet_topup', 'Wallet top-up')], max_length=30)),
                ('object_id', models.PositiveBigIntegerField(blank=True, help_text="Paid object's primary key.", null=True)),
                ('reference', models.CharField(blank=True, help_text='Human readable reference.', max_length=60)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='initiated', max_length=10)),
                ('authority', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('ref_id', models.CharField(blank=True, max_length=64)),
                ('card_pan', models.CharField(blank=True, max_length=32)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['purpose', 'object_id'], name='payments_pa_purpose_a507ea_idx')],
            },
        ),
    ]
