# Generated by Django 5.2.17 on 2026-10-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='description',
        ),
        migrations.RemoveField(
            model_name='team',
            name='game',
        ),
        migrations.RemoveField(
            model_name='team',
            name='max_members',
        ),
        migrations.RemoveField(
            model_name='team',
            name='region',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tag',
        ),
    ]
