# Generated by Django 5.2.17 on 2026-10-03 12:56

from django.db import migrations, models


def backfill_option_summaries(apps, schema_editor):
    """Products that already have options get their cached price range and total stock."""
    Product = apps.get_model("catalog", "Product")
    ProductVariant = apps.get_model("catalog", "ProductVariant")
    for product_id in ProductVariant.objects.values_list("product_id", flat=True).distinct():
        variants = list(ProductVariant.objects.filter(product_id=product_id).order_by("price", "sort_order", "pk"))
        stocks = [variant.stock for variant in variants]
        Product.objects.filter(pk=product_id).update(
            has_variants=True,
            price=variants[0].price,
            original_price=variants[0].original_price,
            price_max=variants[-1].price,
            stock=None if None in stocks else sum(stocks),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_variants',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='price_max',
            field=models.PositiveBigIntegerField(blank=True, editable=False, help_text='Most expensive option; empty for fixed-price products.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, help_text='Required for fixed-price products. With options it is the cheapest option (automatic).', null=True, verbose_name='price (toman)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, help_text='Empty means unlimited. With options it is their total stock (automatic).', null=True),
        ),
        migrations.RunPython(backfill_option_summaries, migrations.RunPython.noop),
    ]
