# Generated by Django 5.2.17 on 2026-10-03 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('system', 'System'), ('tournament', 'Tournament'), ('team_invite', 'Team invitation'), ('team', 'Team'), ('friend_request', 'Friend request'), ('order', 'Order'), ('payment', 'Payment')], default='system', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Action payload consumed by the frontend.')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx')],
            },
        ),
    ]
